<?php

namespace Models\Lists;

use Bitrix\Main\Entity\ReferenceField;
use Models\AbstractIblockPropertyValuesTable;

class DoctorsPropertyValuesTable extends AbstractIblockPropertyValuesTable
{
    const IBLOCK_ID = 16;
    public static function getMap(): array
    {
        $map = [
            'PROCEDURES_DATA' => new ReferenceField(
                'PROCEDURES', 
                ProceduresPropertyValuesTable::class, 
                ['=this.PROCEDURES' => 'ref.IBLOCK_ELEMENT_ID']
            )
        ];

        return parent::getMap() + $map; // TODO: Change the autogenerated stub

    }
}